name: Ubuntu 18.04 - LuppiLandia

on: 
  workflow_dispatch:
    inputs:
      chrome_access_code:
        description: Code for remote-desktop
        required: true
      pin:
        description: Enter your 6 numbers pin
        required: true
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Running settings.sh
        run: |
          sudo bash ./linux_config/setting.sh
          ${{ github.event.inputs.chrome_access_code }} -pin=${{ github.event.inputs.pin }}
      - name: Ubuntu ready to go
        run: sleep 7d
